In [0]:
import numpy as np
syn0 = 2*np.random.random((3,1)) - 1


In [0]:
np.random.seed(1)

In [0]:
syn1 = 2*np.random.random((3,1)) - 1

print(syn1)

[[-0.5910955 ]
 [ 0.75623487]
 [-0.94522481]]


In [0]:
np.random.seed()
print(np.random.random((3,2)))

[[0.94531055 0.45221724]
 [0.67011154 0.57099674]
 [0.3149981  0.28348778]]


In [0]:
import numpy as np
# sigmoid function
def nonlin(x,deriv=False):
  if(deriv==True):
     return x*(1-x)
  return 1/(1+np.exp(-x))
# input dataset
X = np.array([ [0,0,1],
[0,1,1],
[1,0,1],
[1,1,1] ])
# output dataset
y = np.array([[0,0,1,1]]).T
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1
for iter in range(10000):
# forward propagation
   l0 = X
   l1 = nonlin(np.dot(l0,syn0))
# how much did we miss?
   l1_error = y - l1
# multiply how much we missed by the
# slope of the sigmoid at the values in l1
   l1_delta = l1_error * nonlin(l1,True)
# update weights
   syn0 += np.dot(l0.T,l1_delta)


In [0]:
print("Output After Training:")
print(l1)
print(l1_error)
print(l1_delta)

Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
[[-0.00966449]
 [-0.00786506]
 [ 0.00641102]
 [ 0.00788043]]
[[-9.24997129e-05]
 [-6.13726376e-05]
 [ 4.08376707e-05]
 [ 6.16117429e-05]]


In [0]:
for iter1 in range(1000):
  l0=X
  l2=nonlin(np.dot(l0,syn0))
  l2_error = y - l2
  l2_delta = l2_error * nonlin(l2,True)
  syn0 += np.dot(l0.T,l2_delta)

  if iter1 in range(0,1000,300):
    print("iteration {} ".format(iter1))
    print(" {} \n".format(l1))
    print("error:\n {} \n".format(l2_error) )
    print("delta:\n {} \n".format(l2_delta) )
  


iteration 0 
 [[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]] 

error:
 [[-0.00607049]
 [-0.00494577]
 [ 0.00403389]
 [ 0.00495226]] 

delta:
 [[-3.66271677e-05]
 [-2.43396965e-05]
 [ 1.62065917e-05]
 [ 2.44034609e-05]] 

iteration 300 
 [[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]] 

error:
 [[-0.00603397]
 [-0.00491608]
 [ 0.00400969]
 [ 0.0049225 ]] 

delta:
 [[-3.61891548e-05]
 [-2.40490399e-05]
 [ 1.60131704e-05]
 [ 2.41117044e-05]] 

iteration 600 
 [[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]] 

error:
 [[-0.00599811]
 [-0.00488692]
 [ 0.00398593]
 [ 0.00489326]] 

delta:
 [[-3.57614721e-05]
 [-2.37652317e-05]
 [ 1.58243045e-05]
 [ 2.38268277e-05]] 

iteration 900 
 [[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]] 

error:
 [[-0.00596287]
 [-0.00485826]
 [ 0.00396258]
 [ 0.00486454]] 

delta:
 [[-3.53437590e-05]
 [-2.34880327e-05]
 [ 1.56398351e-05]
 [ 2.35485904e-05]] 



In [0]:
print(l2)
print(l2_error)
print(l2_delta)

[[0.00595137]
 [0.00484891]
 [0.99604503]
 [0.99514483]]
[[-0.00595137]
 [-0.00484891]
 [ 0.00395497]
 [ 0.00485517]]
[[-3.52080424e-05]
 [-2.33979683e-05]
 [ 1.55798990e-05]
 [ 2.34581898e-05]]


In [0]:
b, c = "Hello", "World!"
print(b[2:5])

llo


In [0]:
print(c[2])

r


In [0]:
a = " Hello, World! "
print(a.split(',')) # returns "Hello, World!"

[' Hello', ' World! ']


In [0]:
txt = "The rain in Spain stays mainly in the plain"
x = "ain" in txt
print(x)

True


In [0]:
print("hi {1} format function {0}".format("is","demo"))

hi demo format function is


In [0]:
print(5//2)
print("%.2f"%(11/7))

2
1.57


In [0]:
thisset = {"apple", "banana", "cherry"}

print("banana" in thisset)

True


In [0]:
thisdict = {
    "s.no":1,
    "model": "model Name",
    "year": 2019
}

In [0]:
print(thisdict.get("model"))

model Name


In [0]:
for i in thisdict:
  print(i) 

s.no
model
year


In [0]:
print(thisdict.values())

dict_values([1, 'model Name', 2019])


In [0]:
for x,y in thisdict.items():
  print("x= {} ".format(x))
  print("y= {} ".format(y))

x= s.no 
y= 1 
x= model 
y= model Name 
x= year 
y= 2019 


In [0]:
lst = [1,2,3]
def foo(a):
  lst.append(a)
  print(lst)

In [0]:
foo(5)

[1, 2, 3, 6, 5]


In [0]:
lst.insert(3,5)
print(lst)

[1, 2, 3, 5, 6]


In [0]:
lst.remove(5)
print(lst)

[1, 2, 3, 6]


In [0]:
numbers=[n for n in range(10)]
print(numbers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [0]:
print(numbers[1:9:2])

[1, 3, 5, 7]


In [0]:
odd = lambda x: bool(x%2)
print(odd(2))

False


In [0]:
numbers[:] = [n for n in range(10) if not odd(n)]
print(numbers)

[0, 2, 4, 6, 8]


In [0]:
def multiplier(mul):
  return[lambda mul, i=i: mul*i for i in range(15)]

print(multiplier(2))

[<function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a5aa840>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a5aac80>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697840>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697730>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a6972f0>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697d08>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697f28>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697950>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a6977b8>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697ae8>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697a60>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a6971e0>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697620>, <function multiplier.<locals>.<listcomp>.<lambda> at 0x7f4f7a697048>, <function multiplie

In [0]:
c="hello"
print(c[0:2])

he


In [0]:
import logging
import threading
import time

def thread_function(name):
    logging.info("Thread %s: starting", name)
    time.sleep(2)
    logging.info("Thread %s: finishing", name)

if __name__ == "__main__":
    format = "%(asctime)s: %(message)s"
    logging.basicConfig(format=format, level=logging.INFO,
                        datefmt="%H:%M:%S")

    logging.info("Main    : before creating thread")
    x = threading.Thread(target=thread_function, args=(2,))
    logging.info("Main    : before running thread")
    x.start()
    logging.info("Main    : wait for the thread to finish")
    # x.join()
    logging.info("Main    : all done")

08:03:46: Main    : before creating thread
08:03:46: Main    : before running thread
08:03:46: Thread 2: starting
08:03:46: Main    : wait for the thread to finish
08:03:46: Main    : all done


In [0]:
def fun_return(a):
  return f"returning {a} from function"

print(fun_return(1))
c= "hi"
print(f"hi {c}")

returning 1 from function
hi hi


#closure

In [0]:
def outer_fun(msg):
  def inner_fun():
    print(f"Printing from inner function: {msg}")
  return inner_fun()

closure = outer_fun("message")
closure 

Printing from inner function: message


In [0]:
from datetime import datetime
print(datetime.now())

2019-10-30 10:44:22.975794


In [0]:
import functools

def debug(func):
    """Print the function signature and return value"""
    @functools.wraps(func)
    def wrapper_debug(*args, **kwargs):
        args_repr = [repr(a) for a in args]                      # 1
        kwargs_repr = [f"{k}={v!r}" for k, v in kwargs.items()]  # 2
        signature = ", ".join(args_repr + kwargs_repr)           # 3
        print(f"Calling {func.__name__}({signature})")
        value = func(*args, **kwargs)
        print(f"{func.__name__!r} returned {value!r}")           # 4
        return value
    return wrapper_debug

In [0]:
print(debug(5))

<function debug.<locals>.wrapper_debug at 0x7efda7e4a0d0>


In [0]:
numbers = [2,3,4,5]
square = lambda x: x*x
print(square(7))
print(list(map(square,numbers)))
list(map(square,numbers))
  

49
[4, 9, 16, 25]


[4, 9, 16, 25]

In [0]:
from functools import reduce 
product = reduce((lambda x, y: x * y),[1, 2, 3, 4])
print(product)

24


In [0]:
x = range(-5, 5) 
#all_less_than_zero = 
list(filter(lambda num: num < 0, x))

[-5, -4, -3, -2, -1]